TES_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_davenx/devel" 
TES_D2D_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_dave2d/${TES_SVN_BRANCH}"
TES_DHD_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_davehd/${TES_SVN_BRANCH}"
TES_CDC_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_cdc/${TES_SVN_BRANCH}"
TES_FBD_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_framebuffer_decompressor/${TES_SVN_BRANCH}"
TES_TOOLS_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_tools"
TES_LIBRARIES_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_libraries"
TES_EVALKIT_SVN_PATH = "svn://svn.hamburg.tes/svn/tes_evalkits/${TES_SVN_BRANCH}"


